[package]
name = "codes-parser"
version = "0.1.0"
edition = "2021"
maintainer = "Aurelien VALADE <aurelien.valade@balena.io>"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
getopts = "0.2"