// This file is autogenerated, please do not edit manually
#ifndef __FRAMES_MANAGEMENT_H__
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ##FEEDBACKS_DECLARATIONS##

// ##INSTRUCTIONS_DECLARATIONS##

// ##CUSTOM_FOOTER##

#endif
