// This file is autogenerated, please do not edit manually
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

inline int strnlen(char* input, size_t len) {
  int position = 0;

  while (position<len){
    if (input[position] == 0) {
      return position;
    }
    position++;
  }
  return -1;
}

