[package]
name = "integration-tests"
version = "0.1.0"
edition = "2024"
authors = ["Aurelien VALADE <wolvi-lataniere>"]

[build-dependencies]
codes-parser = {path = "../"}
bindgen = "0.72.0"
cc="1.2.32"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
