[package]
name = "integration-tests"
version = "0.1.0"
edition = "2024"
authors = ["Aurelien VALADE <wolvi-lataniere>"]

[target.aarch64-apple-darwin]
profiler=true

[dev-dependencies]

[build-dependencies]
codes-parser = {path = "../"}
bindgen = "0.72.0"
cc="1.2.32"
